import {
  BrainCircuit,
  UserRound,
  ShieldCheck,
  Database,
  Briefcase,
  Gauge,
  Fingerprint,
  FileText,
  Wallet,
  Home,
  ScanSearch,
  ClipboardCheck,
  Landmark,
  GraduationCap,
  type LucideIcon,
} from "lucide-react";

export type GlossaryTerm = {
  term: string;
  short: string;
  /** Shown when the entry is expanded. */
  detail: string;
  icon: LucideIcon;
};

/**
 * Glossary entries, kept as plain data so new terms can be added without
 * touching the page — the letter index and counts derive from this list.
 */
export const glossaryTerms: GlossaryTerm[] = [
  {
    term: "AI Decision Engine",
    short:
      "The core of Verify Engine that uses artificial intelligence and machine learning to analyze data, evaluate risk, and generate verification results.",
    detail:
      "The engine weighs every verified data point against your configured rules, flags inconsistencies, and produces an explainable recommendation rather than an opaque yes or no.",
    icon: BrainCircuit,
  },
  {
    term: "Applicant",
    short:
      "The individual who submits information to be verified. This can include tenants, job candidates, borrowers, students, or patients depending on the use case.",
    detail:
      "Applicants consent to verification as part of your application flow, and can be re-verified later without resubmitting everything.",
    icon: UserRound,
  },
  {
    term: "Background Check",
    short:
      "A verification process that may include criminal records, eviction history, credit history, employment history, and other public records.",
    detail:
      "Which components are permitted varies by jurisdiction and use case, so your configured criteria determine what is actually run.",
    icon: ShieldCheck,
  },
  {
    term: "Data Source",
    short:
      "A third-party provider or database that supplies information used in the verification process, such as credit bureaus, payroll providers, or public records.",
    detail:
      "Every result records which source it came from and when, so a report can be traced back to its origin during an audit.",
    icon: Database,
  },
  {
    term: "Employment Verification",
    short:
      "The process of confirming an applicant's current or past employment details, including job title, dates of employment, and income.",
    detail:
      "Verify Engine reaches the employer directly rather than relying on documents the applicant supplies, which removes the easiest point of falsification.",
    icon: Briefcase,
  },
  {
    term: "Fraud Risk Score",
    short:
      "A score generated by Verify Engine that indicates the likelihood of fraudulent activity based on patterns and anomalies in the applicant's data.",
    detail:
      "The score is a signal, not a decision. It highlights where a human reviewer should look before a result is released.",
    icon: Gauge,
  },
  {
    term: "Identity Verification",
    short:
      "The process of confirming that an individual is who they claim to be by validating identity documents and comparing data across trusted sources.",
    detail:
      "Identity is verified first, because every other check is only meaningful once the subject is confirmed.",
    icon: Fingerprint,
  },
  {
    term: "Income Verification",
    short:
      "Confirmation of an applicant's income amount, source, frequency, and stability over time.",
    detail:
      "Verifying at the payroll or employer level rather than from pay stubs removes the most commonly falsified document in an application.",
    icon: Wallet,
  },
  {
    term: "Landlord Verification",
    short:
      "Confirmation of an applicant's rental history with previous landlords, covering payment timeliness, lease compliance, and condition at move-out.",
    detail:
      "Verify Engine's flagship product, run by AI voice agents that call previous landlords and conduct a structured interview.",
    icon: Home,
  },
  {
    term: "Human Quality Review",
    short:
      "The step where a trained analyst reviews an AI-generated verification before the report is released.",
    detail:
      "Reviewers listen to the call, confirm the extracted data, and add confidence notes — the step that makes results defensible when questioned.",
    icon: ClipboardCheck,
  },
  {
    term: "Mortgage Verification",
    short:
      "Confirmation of mortgage accounts, monthly payment amounts, loan status, and property address with the lender or servicer.",
    detail:
      "Used by lenders and landlords alike to understand an applicant's existing housing obligations.",
    icon: Landmark,
  },
  {
    term: "Education Verification",
    short:
      "Confirmation of degrees, diplomas, enrollment, and certifications with the issuing institution.",
    detail:
      "Verified with registrars and clearinghouses rather than from a transcript copy provided by the applicant.",
    icon: GraduationCap,
  },
  {
    term: "Verification Report",
    short:
      "A comprehensive report generated by Verify Engine that summarizes all completed verifications, results, and risk assessments.",
    detail:
      "Includes the full transcript, audit trail, and VE Score breakdown, and can be downloaded as a PDF for your records.",
    icon: FileText,
  },
  {
    term: "VE Score™",
    short:
      "Verify Engine's proprietary score summarizing an applicant's verification outcome on a 0–100 scale.",
    detail:
      "The score is always accompanied by the factors that produced it, so you can see why a result landed where it did.",
    icon: Gauge,
  },
  {
    term: "Watchlist Screening",
    short:
      "A check against sanctions, enforcement, and other watchlists relevant to regulated onboarding.",
    detail:
      "Common in financial services onboarding, where a clear result is a compliance requirement rather than a preference.",
    icon: ScanSearch,
  },
];

/** Letters that actually have entries, with their counts. */
export function glossaryLetters() {
  const counts = new Map<string, number>();
  for (const entry of glossaryTerms) {
    const letter = entry.term[0].toUpperCase();
    counts.set(letter, (counts.get(letter) ?? 0) + 1);
  }
  return [...counts.entries()].sort(([a], [b]) => a.localeCompare(b));
}
